### ISSUE TITLE
Feature request : Add an option to disable compile on keypress 

### ISSUE THREAD

**Issue by akkolad** [ffd8/HY5LIVE#1]
Hello Ted,

I love Hydra, I love P5.js and I love your projects P5LIVE and HY5LIVE.
I use P5LIVE and Hydra during live-coding events and for vjing.
You made my dream come true with HY5LIVE.
But I can't use it for vjing because "HY5LIVE tries to automatically compile your code on every keypress".
This option constantly generates display rendering errors, making vjing impossible.
Can you add an option in the setting tab to disable this feature ?

Thanks.

**Comment by ffd8** [comment]
Hey @akkolad – thaanks and that's a very reasonable request, haha though I loved that it just forces each keystroke to compile as a 'this is possible + no other editor has that action' with lots of error correction. Nevertheless, perhaps there's not enough error correction and it's possible to go boom, when I just do a quick 'hard compile' (`CMD + SHIFT + ENTER`). 

In P5LIVE one can disable auto-compiling and/or slow it down to wait as much as 2sec after keypress. But adding it to this could be easily done too. I was just keeping it as minimal an editor as possible, testing out alternative ways of doing things to P5LIVE etc etc, before realizing that HY5 could just be a library on it's own and used anywhere, rather than only in HY5LIVE. Nevertheless one needs a few lines less of code when using HY5LIVE vs P5LIVE, since the libs attachment and sandbox are all in the background hidden from the editor.

Have you checked out the latest version of P5LIVE (1.5.0), which also has many demos and snippets for using HY5 within it? I see HY5LIVE as an experimental, minimal editor – where saving sketches acts more as readonly templates for jamming, whereas P5LIVE is way further developed and definitely more stable. Would love to hear what aspects of HY5LIVE you prefer...

**Comment by akkolad** [comment]
Hey, great! I didn’t see the addition of HY5 and the snippets (hy5-p5-hydra) in P5LIVE. That solves my problem!
Thanks again for your amazing work for the community.
Cheers.
